[package]
name = "world-domination"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
]
